### ISSUE TITLE
Handle server side errors

### ISSUE THREAD

**Issue by SLeitgeb** [gis4dis/mc-client#28] opened 2018-09-06 11:01 UTC
If a server request returns an error (e.g. 500 Internal Server Error on this endpoint: http://localhost:8000/api/v1/timeseries/?name_id=air_temperature&phenomenon_date_from=2018-08-06&phenomenon_date_to=2018-09-05), an error message is displayed: “An unexpected error has occurred.” and the application becomes unusable. I suggest e.g. displaying an error prompt and allowing the user to change the data time range or extent to produce a different request, handle it automatically or display at least an empty map.

**Comment by jirik** [comment] 2018-09-06 14:37
@SLeitgeb Is relevant also the following message, you've reported to me?

> Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by kordilery** [comment] 2018-09-06 18:08
Problem was caused by newly added feature popup. Fixed in commit:#9f7c0dd

**Closed by kordilery** 2018-09-06 18:08 UTC
