### ISSUE TITLE
Error in production, strange date range

### ISSUE THREAD

**Issue by jirik** [gis4dis/mc-client#34] opened 2018-10-10 16:55 UTC
After the default request
/api/v2/timeseries/?format=json&phenomenon_date_from=2018-09-10&phenomenon_date_to=2018-10-09&topic=drought
to production server the map show strange date range. The values after initial thumb position exist, values before do not. Moving thumb before it's initial position break app down.

![image](https://user-images.githubusercontent.com/2271850/46752529-c32a1380-ccbd-11e8-8642-f5e5527e4038.png)

**Comment by kordilery** [comment] 2018-10-11 18:52
The problem was caused by asynchronous setting of properties, should be fixed by commit:#dc0fada.

**Closed by kordilery** 2018-10-11 18:52 UTC
Labels: bug
